version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123@"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    restart: always
    networks:
      - app-network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyStore;User Id=sa;Password=Password123@;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge